### ISSUE TITLE
defaultColor in the constructor of AdvancementDisplay doesn't work

### ISSUE THREAD

**Issue by D-Hydrogen** [frengor/UltimateAdvancementAPI#36] opened 2023-01-25 10:02 UTC
When I put a ChatColor object into the constructor
`public AdvancementDispay(icon, title, frame, showToast, announceChat, x, y, defaultCOlor, description)`
there isn't any effect and the color doesn't change.
For some reason I have to use 1.19.3paper, is that the cause?
thanks.

**Comment by EscanorTargaryen** [comment] 2023-01-26 19:47
Hi, could you show us some screenshots of what is happening and the code you are using?

**Comment by frengor** [comment] 2023-09-26 22:28
Closing since we cannot reproduce the bug

**Closed by frengor** 2023-09-26 22:28 UTC
Labels: question
